export const countries = [
  { id: 'FWC', name: 'FWC (Intro y Anfitrionas)', pages: 'Págs. 1-3 y 106-109', flag: '🏆', total: 19 },
  { id: 'MEX', name: 'México', pages: 'Págs. 8-9', flag: '🇲🇽', total: 20 },
  { id: 'RSA', name: 'Sudáfrica', pages: 'Págs. 10-11', flag: '🇿🇦', total: 20 },
  { id: 'KOR', name: 'Corea del Sur', pages: 'Págs. 12-13', flag: '🇰🇷', total: 20 },
  { id: 'CZE', name: 'República Checa', pages: 'Págs. 14-15', flag: '🇨🇿', total: 20 },
  { id: 'CAN', name: 'Canadá', pages: 'Págs. 16-17', flag: '🇨🇦', total: 20 },
  { id: 'BIH', name: 'Bosnia', pages: 'Págs. 18-19', flag: '🇧🇦', total: 20 },
  { id: 'QAT', name: 'Qatar', pages: 'Págs. 20-21', flag: '🇶🇦', total: 20 },
  { id: 'SUI', name: 'Suiza', pages: 'Págs. 22-23', flag: '🇨🇭', total: 20 },
  { id: 'BRA', name: 'Brasil', pages: 'Págs. 24-25', flag: '🇧🇷', total: 20 },
  { id: 'MAR', name: 'Marruecos', pages: 'Págs. 26-27', flag: '🇲🇦', total: 20 },
  { id: 'HAI', name: 'Haití', pages: 'Págs. 28-29', flag: '🇭🇹', total: 20 },
  { id: 'SCO', name: 'Escocia', pages: 'Págs. 30-31', flag: '🏴󠁧󠁢󠁳󠁣󠁴󠁿', total: 20 },
  { id: 'USA', name: 'EE.UU.', pages: 'Págs. 32-33', flag: '🇺🇸', total: 20 },
  { id: 'PAR', name: 'Paraguay', pages: 'Págs. 34-35', flag: '🇵🇾', total: 20 },
  { id: 'AUS', name: 'Australia', pages: 'Págs. 36-37', flag: '🇦🇺', total: 20 },
  { id: 'TUR', name: 'Turquía', pages: 'Págs. 38-39', flag: '🇹🇷', total: 20 },
  { id: 'GER', name: 'Alemania', pages: 'Págs. 40-41', flag: '🇩🇪', total: 20 },
  { id: 'CUW', name: 'Curazao', pages: 'Págs. 42-43', flag: '🇨🇼', total: 20 },
  { id: 'CIV', name: 'Costa de Marfil', pages: 'Págs. 44-45', flag: '🇨🇮', total: 20 },
  { id: 'ECU', name: 'Ecuador', pages: 'Págs. 46-47', flag: '🇪🇨', total: 20 },
  { id: 'NED', name: 'Países Bajos', pages: 'Págs. 48-49', flag: '🇳🇱', total: 20 },
  { id: 'JPN', name: 'Japón', pages: 'Págs. 50-51', flag: '🇯🇵', total: 20 },
  { id: 'SWE', name: 'Suecia', pages: 'Págs. 52-53', flag: '🇸🇪', total: 20 },
  { id: 'TUN', name: 'Túnez', pages: 'Págs. 54-55', flag: '🇹🇳', total: 20 },
  { id: 'BEL', name: 'Bélgica', pages: 'Págs. 58-59', flag: '🇧🇪', total: 20 },
  { id: 'EGY', name: 'Egipto', pages: 'Págs. 60-61', flag: '🇪🇬', total: 20 },
  { id: 'IRN', name: 'Irán', pages: 'Págs. 62-63', flag: '🇮🇷', total: 20 },
  { id: 'NZL', name: 'Nueva Zelanda', pages: 'Págs. 64-65', flag: '🇳🇿', total: 20 },
  { id: 'ESP', name: 'España', pages: 'Págs. 66-67', flag: '🇪🇸', total: 20 },
  { id: 'CPV', name: 'Cabo Verde', pages: 'Págs. 68-69', flag: '🇨🇻', total: 20 },
  { id: 'KSA', name: 'Arabia Saudita', pages: 'Págs. 70-71', flag: '🇸🇦', total: 20 },
  { id: 'URU', name: 'Uruguay', pages: 'Págs. 72-73', flag: '🇺🇾', total: 20 },
  { id: 'FRA', name: 'Francia', pages: 'Págs. 74-75', flag: '🇫🇷', total: 20 },
  { id: 'SEN', name: 'Senegal', pages: 'Págs. 76-77', flag: '🇸🇳', total: 20 },
  { id: 'IRQ', name: 'Irak', pages: 'Págs. 78-79', flag: '🇮🇶', total: 20 },
  { id: 'NOR', name: 'Noruega', pages: 'Págs. 80-81', flag: '🇳🇴', total: 20 },
  { id: 'ARG', name: 'Argentina', pages: 'Págs. 82-83', flag: '🇦🇷', total: 20 },
  { id: 'ALG', name: 'Argelia', pages: 'Págs. 84-85', flag: '🇩🇿', total: 20 },
  { id: 'AUT', name: 'Austria', pages: 'Págs. 86-87', flag: '🇦🇹', total: 20 },
  { id: 'JOR', name: 'Jordania', pages: 'Págs. 88-89', flag: '🇯🇴', total: 20 },
  { id: 'POR', name: 'Portugal', pages: 'Págs. 90-91', flag: '🇵🇹', total: 20 },
  { id: 'COD', name: 'Congo', pages: 'Págs. 92-93', flag: '🇨🇩', total: 20 },
  { id: 'UZB', name: 'Uzbekistán', pages: 'Págs. 94-95', flag: '🇺🇿', total: 20 },
  { id: 'COL', name: 'Colombia', pages: 'Págs. 96-97', flag: '🇨🇴', total: 20 },
  { id: 'ENG', name: 'Inglaterra', pages: 'Págs. 98-99', flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', total: 20 },
  { id: 'CRO', name: 'Croacia', pages: 'Págs. 100-101', flag: '🇭🇷', total: 20 },
  { id: 'GHA', name: 'Ghana', pages: 'Págs. 102-103', flag: '🇬🇭', total: 20 },
  { id: 'PAN', name: 'Panamá', pages: 'Págs. 104-105', flag: '🇵🇦', total: 20 }
];
